### ISSUE TITLE
Ducktape

### ISSUE THREAD

**Issue by imcdo** [asatarin/testing-distributed-systems#14]
Hi came across this when doing some research into how others test their distributed systems.  Just wanted to bring to your attention `ducktape` github.com/confluentinc/ducktape.  This is how we test [apache kafka](https://github.com/apache/kafka/tree/trunk/tests/kafkatest) (also used by things like apache ignite and redpanda). 

Ducktape is a testing framework meant to test multiple independent distributed systems procedurally.   

Anyways I gave a talk about it here: https://www.confluent.io/en-gb/events/current-2022/ducktape-keeping-system-testing-simple-in-a-distributed-world/ if it interests you.  Just thought i might bring it to your attention. 

Thanks for such a great resource here!

**Comment by asatarin** [comment]
Hi Ian,

Video is behind register wall, unfortunately. 

Skimmed tests and they seem to be either functional or benchmarks, is this correct?

**Comment by imcdo** [comment]
Yes, yeah the video is behind a survey my bad.  Yes it's a functional framework

**Comment by imcdo** [comment]
https://ducktape.readthedocs.io/en/latest/ here is the read the docs to if it interests you

**Comment by asatarin** [comment]
Don't think yet another functional testing framework adds anything to the conversation.
